version: '3.9'

services:
  mongo:
    container_name: dashboards-mongo
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=root-db
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
